### PR TITLE
Fix dependencies.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by abencz** [comment]
Thanks for the PR! Unfortunately this breaks support for Racket 5.3 which is still the default on Ubuntu 14.04 :(

Is there a way to have the package support both Racket 5.3 and 6+?

**Comment by samth** [comment]
What's the error you get on 5.3?

Sam

**Comment by abencz** [comment]
I get this:

```
$ make link
raco pkg install --link -n socketcan $(pwd)
raco pkg install: missing dependencies
 for package: /home/travis/build/abencz/racket-socketcan
 missing packages:
   base
   make
make: *** [link] Error 1
```

From what I understand 5.3.6 doesn't actually have "base" and "make" as modules?

**Comment by abencz** [comment]
See also the Travis CI build: https://travis-ci.org/abencz/racket-socketcan/jobs/62777630

**Comment by samth** [comment]
One thing to do here is to specify different versions for 5.3 and for 6.1.1. You can do this as two different branches in GitHub.

@mflatt @jeapostrophe Do either of you know if there's anything that will work on 5.3?

**Comment by mflatt** [comment]
I think there's no package to depend on for v5.3.x. The content of the "base" and "make" packages was effectively built-in before v6.0.

**Comment by abencz** [comment]
Thanks @samth! The ability to specify different branches for different versions is just what I needed, although it took a little while to figure out how to configure it.

**Pull request merged**
